### PR TITLE
Slim and ERB

### PR DESCRIPTION
**Pull request by siassaj**
Yo, Slim's working ok although markdown mode doesn't play nice. It looks to be an issue with markdown-mode but it'd probably be good if we could 'lie' to the inner modes about where their 0 column is.

ERB is there too for html, js and coffee files but I've not put it in the README because of the issue we discussed (open delimiters on one side of an erb block don't match to the closing delimiter on the other side).

### CODE REVIEW

**Comment by siassaj** [comment]
I have no idea how this works after 2 months :0

**Comment by siassaj** [comment]
@vspinu I did it. Renamed it to 'indented-block' to keep a cohesiveness and terse name. Also moved it to that file you mentioned.

**Comment by vspinu** [comment]
Thanks! Looks great.

**Comment by siassaj** [comment]
any idea how to make the inner mode think that the left indent level is the 0 column?

**Comment by vspinu** [comment]
Why do you need this? 

The indentation is done through `pm-indent-line-dispatcher` and all the work is done in `pm-indent-line`. I think the indentation is hardcoded to be relative to the chunk head.

**Comment by siassaj** [comment]
markdown mode uses column 0 for all headers. It doesn't highlight properly if the ##headers are not on that 0 column...

**Pull request merged**
